NAME = "single_dws_conv_non_divisible"

[global]
BW = 16
WBW = 16
NUM_FRAC_BITS = 0
FREQ = 200
COEFF_ON_CHIP = true
USE_DRAM = true

[layers.conv0]
H = 2
W = 2
C = 3
F = 3
K = 3
S = 1
P = 1
P_C = [2]
P_F = [2]
TYPE = "DEPTHWISE_SEPARABLE"
