NAME = "single_conv_par"

[global]
BW = 16
WBW = 16
NUM_FRAC_BITS = 0
FREQ = 200
COEFF_ON_CHIP = true
USE_DRAM = true

[layers.conv0]
H = 2
W = 2
C = 4
F = 4
P_C = 2
P_F = 2
K = 3
S = 1
P = 1
TYPE = "STANDARD"
