NAME = "resnet_18"

[global]
BW = 8
WBW = 2
NUM_FRAC_BITS = 0
FREQ = 300
USE_DRAM = true
COEFF_ON_CHIP = true

[layers.conv0]
H = 112
W = 112
C = 3
F = 64
K = 3
P = 1
S = 2
NUM_OUTPUTS = 2
NAMED_REGION = "SLR0"
TYPE = "STANDARD"

# conv2_x

[layers.conv1]
H = 56
W = 56
C = 64
F = 64
K = 3
P = 1
S = 2
SEQ = 1
INPUT = "conv0"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR0"
TYPE = "STANDARD"

[layers.conv2]
H = 56
W = 56
C = 64
F = 64
K = 3
P = 1
S = 1
INPUT = "conv1"
NUM_OUTPUTS = 2
RESIDUAL = "conv0_1"
NAMED_REGION = "SLR0"
TYPE = "STANDARD"

[layers.conv3]
H = 56
W = 56
C = 64 
F = 64
K = 3
P = 1
S = 1
INPUT = "conv2"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR0"
TYPE = "STANDARD"

[layers.conv4]
H = 56
W = 56
C = 64
F = 64
K = 3
P = 1
S = 1
INPUT = "conv3"
NUM_OUTPUTS = 2
RESIDUAL = "conv2_1"
NAMED_REGION = "SLR0"
TYPE = "STANDARD"

# conv3_x

[layers.conv5]
H = 28
W = 28
C = 64
F = 128
K = 3
P = 1
S = 2
INPUT = "conv4"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR0"
TYPE = "STANDARD"

[layers.shortcut2]
H = 28
W = 28
C = 64
F = 128
K = 1
P = 0
S = 2
INPUT = "conv4_1"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR1"
TYPE = "POINTWISE"

[layers.conv6]
H = 28
W = 28
C = 128
F = 128
K = 3
P = 1
S = 1
INPUT = "conv5"
NUM_OUTPUTS = 2
RESIDUAL = "shortcut2"
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

[layers.conv7]
H = 28 
W = 28 
C = 128 
F = 128
K = 3
P = 1
S = 1
INPUT = "conv6"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

[layers.conv8]
H = 28
W = 28
C = 128
F = 128
K = 3
P = 1
S = 1
INPUT = "conv7"
NUM_OUTPUTS = 2
RESIDUAL = "conv6_1"
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

# conv4_x

[layers.conv9]
H = 14
W = 14
C = 128
F = 256
K = 3
P = 1
S = 2
INPUT = "conv8"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

[layers.shortcut3]
H = 14
W = 14
C = 128
F = 256
K = 1
P = 0
S = 2
INPUT = "conv8_1"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR1"
TYPE = "POINTWISE"

[layers.conv10]
H = 14 
W = 14 
C = 256
F = 256
K = 3
P = 1
S = 1
INPUT = "conv9"
NUM_OUTPUTS = 2
RESIDUAL = "shortcut3"
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

[layers.conv11]
H = 14 
W = 14 
C = 256 
F = 256
K = 3
P = 1
S = 1
INPUT = "conv10"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

[layers.conv12]
H = 14 
W = 14 
C = 256 
F = 256 
K = 3
P = 1
S = 1
INPUT = "conv11"
NUM_OUTPUTS = 2
RESIDUAL = "conv10_1"
NAMED_REGION = "SLR1"
TYPE = "STANDARD"

# conv5_x

[layers.conv13]
H = 7
W = 7
C = 256
F = 512
K = 3
P = 1
S = 2
P_F = 4
INPUT = "conv12"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR2"
TYPE = "STANDARD"

[layers.shortcut4]
H = 7
W = 7
C = 256
F = 512
K = 1
P = 0
S = 2
P_F = 4
INPUT = "conv12_1"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR2"
TYPE = "POINTWISE"

[layers.conv14]
H = 7
W = 7
C = 512 
F = 512 
K = 3
P = 1
S = 1
P_C = 4
P_F = 4
INPUT = "conv13"
NUM_OUTPUTS = 2
RESIDUAL = "shortcut4"
NAMED_REGION = "SLR2"
TYPE = "STANDARD"

[layers.conv15]
H = 7 
W = 7 
C = 512 
F = 512
K = 3
P = 1
S = 1
P_C = 4
P_F = 4
INPUT = "conv14"
NUM_OUTPUTS = 1
NAMED_REGION = "SLR2"
TYPE = "STANDARD"

[layers.conv16]
H = 7 
W = 7 
C = 512 
F = 512 
K = 3
P = 1
S = 1
P_C = 4
P_F = 4
INPUT = "conv15"
NUM_OUTPUTS = 1
RESIDUAL = "conv14_1"
NAMED_REGION = "SLR2"
TYPE = "STANDARD"
