#!/usr/bin/env bash

DIR="$(dirname "$(dirname "$(realpath "$0")")")"
PAR=20

python3 "${DIR}/evaluation/scripts/tool.py" --cfg "${DIR}/evaluation/configs/unittest" -j "${PAR}" -d "${DIR}/evaluation/unittest" gen
python3 "${DIR}/evaluation/scripts/tool.py" --cfg "${DIR}/evaluation/configs/unittest" -j "${PAR}" -d "${DIR}/evaluation/unittest" runsim --dbg
